export default {
    tintColor: "#cc0200",
    tabIconDefault: "#ccc",
    tabIconSelected: "#2f95dc",
    tabBar: "#fff",
    errorBackground: "red",
    errorText: "#fff",
    warningBackground: "#EAEB5E",
    warningText: "#666804",
    noticeBackground: "#2f95dc",
    noticeText: "#fff",
    bearBrown: "#7d5125",
    starYellow: "#ffef26",
    danger: "#db3737",
    warning: "#d9822b",
    success: "#0f9960",
    inactiveIcon: "#CCCCCC",
    activeIcon: "#949494",
    accentRed: "#CC0200",
};
